INCSDIR= /usr/include/cputwo

INCS=	ansi.h asm.h atomic.h \
	bswap.h \
	cdefs.h cpu.h cpuconf.h cpu_counter.h \
	disklabel.h \
	elf_machdep.h endian.h \
	float.h frame.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	limits.h lock.h \
	math.h mcontext.h mutex.h \
	param.h pcb.h proc.h profile.h \
	rwlock.h \
	setjmp.h signal.h \
	trap.h types.h \
	vmparam.h \
	wchar_limits.h

.include <bsd.kinc.mk>
